import { Card } from "./types";

export const MAJORS: Card[] = [
  {
    id: "MAJ_00_FOOL",
    name: "The Fool · Signal Zero",
    arcana: "Major",
    suit: null,
    rank: "0",
    element: "Air",
    astro: { type: "element", key: "Air" },
    house_hook: 0,
    hebrew: "Aleph",
    decan_index: 0,
    poem_slot: "P01",
    upright: "Open channel to unknown terrain.",
    shadow: "Wandering without telemetry.",
  },
  {
    id: "MAJ_01_MAGICIAN",
    name: "The Magician · Signal Router",
    arcana: "Major",
    suit: null,
    rank: "1",
    element: "Air",
    astro: { type: "planet", key: "Mercury" },
    house_hook: 1,
    hebrew: "Beth",
    decan_index: 0,
    poem_slot: "P02",
    upright: "Craft the packet, route the myth.",
    shadow: "Manipulate channels for noise.",
  },
  {
    id: "MAJ_02_PRIESTESS",
    name: "High Priestess · Moon Bridge",
    arcana: "Major",
    suit: null,
    rank: "2",
    element: "Water",
    astro: { type: "planet", key: "Moon" },
    house_hook: 2,
    hebrew: "Gimel",
    decan_index: 0,
    poem_slot: "P03",
    upright: "Intuition syncs with silent data.",
    shadow: "Secrets stall the signal.",
  },
  {
    id: "MAJ_04_EMPEROR",
    name: "The Emperor · Regime Architect",
    arcana: "Major",
    suit: null,
    rank: "4",
    element: "Fire",
    astro: { type: "sign", key: "Aries" },
    house_hook: 4,
    hebrew: "Heh",
    decan_index: 0,
    poem_slot: "P04",
    upright: "Authority sets the frame for force.",
    shadow: "Control calcifies into rigidity.",
  },
  {
    id: "MAJ_10_WHEEL",
    name: "Wheel of Fortune · Orbit Shift",
    arcana: "Major",
    suit: null,
    rank: "10",
    element: "Fire",
    astro: { type: "planet", key: "Jupiter" },
    house_hook: 10,
    hebrew: "Kaph",
    decan_index: 0,
    poem_slot: "P05",
    upright: "Cycles expand; luck favors momentum.",
    shadow: "Spin without steering the helm.",
  },
  {
    id: "MAJ_19_SUN",
    name: "The Sun · Reactor Core",
    arcana: "Major",
    suit: null,
    rank: "19",
    element: "Fire",
    astro: { type: "planet", key: "Sun" },
    house_hook: 19,
    hebrew: "Resh",
    decan_index: 0,
    poem_slot: "P06",
    upright: "Vital clarity fuels every system.",
    shadow: "Overexposure scorches nuance.",
  },
  {
    id: "MAJ_21_WORLD",
    name: "The World · Systems Loop",
    arcana: "Major",
    suit: null,
    rank: "21",
    element: "Earth",
    astro: { type: "element", key: "Earth" },
    house_hook: 21,
    hebrew: "Tav",
    decan_index: 0,
    poem_slot: "P07",
    upright: "Integration locks the circuit closed.",
    shadow: "Completion resists the next upgrade.",
  },
];
