#!/usr/bin/env bash
set -euo pipefail

# Build a clean, metadata-scrubbed PDF bundle from files in /mnt/user-data/outputs.
#
# Usage:
#   ./scripts/build_syvaq_package.sh
#
# Output:
#   /mnt/user-data/outputs/SYVAQ_Master_Package_2026-03-01_individual_clean.zip

SRC_DIR="/mnt/user-data/outputs"
WORK_DIR="${HOME}/SYVAQ_clean_individual_$(date +%Y%m%d%H%M%S)"
OUT_ZIP="/mnt/user-data/outputs/SYVAQ_Master_Package_2026-03-01_individual_clean.zip"
CLEAN_PDF_NAME_PREFIX="SYVAQ_CLEAN_"

mkdir -p "$WORK_DIR"
echo "Working directory: $WORK_DIR"

rsync -av --progress --exclude='*.zip' "$SRC_DIR"/ "$WORK_DIR"/
cd "$WORK_DIR"

shopt -s nullglob
for f in *.docx *.doc *.xlsx *.xls; do
  echo "Converting: $f -> PDF"
  soffice --headless --convert-to pdf --outdir "$WORK_DIR" "$f" >/dev/null 2>&1 || {
    echo "Warning: LibreOffice conversion failed for $f"
  }
done

for f in *.odt *.ods *.pptx *.ppt; do
  echo "Converting: $f -> PDF"
  soffice --headless --convert-to pdf --outdir "$WORK_DIR" "$f" >/dev/null 2>&1 || true
done

i=1
for pdf in *.pdf; do
  base=$(basename "$pdf")
  new="${CLEAN_PDF_NAME_PREFIX}$(printf "%02d" "$i")_${base// /_}"
  if [[ "$pdf" != "$new" ]]; then
    mv -n "$pdf" "$new"
    pdf="$new"
  fi
  echo "Prepared PDF: $pdf"
  i=$((i + 1))
done

if command -v exiftool >/dev/null 2>&1; then
  echo "Stripping PDF metadata with exiftool..."
  exiftool -all= -overwrite_original --ext pdf .
else
  echo "exiftool not found; skipping metadata stripping"
fi

if command -v gs >/dev/null 2>&1; then
  echo "Flattening PDFs with Ghostscript..."
  for pdf in ${CLEAN_PDF_NAME_PREFIX}*.pdf; do
    tmp="${pdf}.gs.tmp.pdf"
    gs -dNOPAUSE -dBATCH -q -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 \
      -dPDFSETTINGS=/printer -sOutputFile="$tmp" "$pdf" && mv -f "$tmp" "$pdf"
  done
else
  echo "Ghostscript (gs) not found; skipping flattening"
fi

if command -v exiftool >/dev/null 2>&1; then
  exiftool -all= -overwrite_original --ext pdf .
fi

echo "Scanning for assistant/tool strings..."
FOUND=false
for f in ${CLEAN_PDF_NAME_PREFIX}*.pdf; do
  if command -v pdftotext >/dev/null 2>&1; then
    pdftotext "$f" - | grep -iE "chatgpt|claude|openai|assistant|generated by" >/dev/null 2>&1 && {
      echo ">>> FOUND possible assistant/tool string in: $f"
      FOUND=true
    }
  else
    strings "$f" | grep -iE "chatgpt|claude|openai|assistant|generated by" >/dev/null 2>&1 && {
      echo ">>> FOUND possible assistant/tool string in: $f (strings grep)"
      FOUND=true
    }
  fi
done

if [[ "$FOUND" == true ]]; then
  echo "WARNING: One or more PDFs may contain assistant/tool strings. Inspect flagged files and rerun."
else
  echo "No assistant/tool strings found in PDFs (quick scan)."
fi

echo "Creating final ZIP: $OUT_ZIP"
rm -f "$OUT_ZIP"
zip -j "$OUT_ZIP" ${CLEAN_PDF_NAME_PREFIX}*.pdf >/dev/null

echo "DONE. Clean package placed at: $OUT_ZIP"
echo "Working directory preserved at: $WORK_DIR"
