/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { type Card } from './types.js';

export const MAJORS: Card[] = [
  {
    id: 'MAJ_00',
    name: 'The Fool',
    arcana: 'Major',
    suit: null,
    rank: '0',
    element: 'Air',
    astro: { type: 'element', key: 'Air' },
    house_hook: 0,
    hebrew: 'Aleph',
    decan_index: 0,
    poem_slot: 'P01',
    upright: 'leap, trust',
    shadow: 'chaos, drift',
  },
  {
    id: 'MAJ_01',
    name: 'The Magician',
    arcana: 'Major',
    suit: null,
    rank: '1',
    element: 'Air',
    astro: { type: 'planet', key: 'Mercury' },
    house_hook: 3,
    hebrew: 'Beth',
    decan_index: 0,
    poem_slot: 'P02',
    upright: 'focus, channel',
    shadow: 'trick, hustle',
  },
  {
    id: 'MAJ_02',
    name: 'High Priestess',
    arcana: 'Major',
    suit: null,
    rank: '2',
    element: 'Water',
    astro: { type: 'planet', key: 'Moon' },
    house_hook: 4,
    hebrew: 'Gimel',
    decan_index: 0,
    poem_slot: 'P03',
    upright: 'intuition, veil',
    shadow: 'secrecy, fog',
  },
  {
    id: 'MAJ_03',
    name: 'The Empress',
    arcana: 'Major',
    suit: null,
    rank: '3',
    element: 'Earth',
    astro: { type: 'planet', key: 'Venus' },
    house_hook: 2,
    hebrew: 'Daleth',
    decan_index: 0,
    poem_slot: 'P04',
    upright: 'growth, body',
    shadow: 'excess, smother',
  },
  {
    id: 'MAJ_04',
    name: 'The Emperor',
    arcana: 'Major',
    suit: null,
    rank: '4',
    element: 'Fire',
    astro: { type: 'sign', key: 'Aries' },
    house_hook: 1,
    hebrew: 'He',
    decan_index: 0,
    poem_slot: 'P05',
    upright: 'structure, will',
    shadow: 'control, rigid',
  },
  {
    id: 'MAJ_05',
    name: 'The Hierophant',
    arcana: 'Major',
    suit: null,
    rank: '5',
    element: 'Earth',
    astro: { type: 'sign', key: 'Taurus' },
    house_hook: 2,
    hebrew: 'Vav',
    decan_index: 0,
    poem_slot: 'P06',
    upright: 'teach, tradition',
    shadow: 'dogma, gate',
  },
  {
    id: 'MAJ_06',
    name: 'The Lovers',
    arcana: 'Major',
    suit: null,
    rank: '6',
    element: 'Air',
    astro: { type: 'sign', key: 'Gemini' },
    house_hook: 3,
    hebrew: 'Zayin',
    decan_index: 0,
    poem_slot: 'P07',
    upright: 'merge, choice',
    shadow: 'split, indecision',
  },
  {
    id: 'MAJ_07',
    name: 'The Chariot',
    arcana: 'Major',
    suit: null,
    rank: '7',
    element: 'Water',
    astro: { type: 'sign', key: 'Cancer' },
    house_hook: 4,
    hebrew: 'Cheth',
    decan_index: 0,
    poem_slot: 'P08',
    upright: 'drive, victory',
    shadow: 'force, tunnel',
  },
  {
    id: 'MAJ_08',
    name: 'Strength',
    arcana: 'Major',
    suit: null,
    rank: '8',
    element: 'Fire',
    astro: { type: 'sign', key: 'Leo' },
    house_hook: 5,
    hebrew: 'Teth',
    decan_index: 0,
    poem_slot: 'P09',
    upright: 'courage, heart',
    shadow: 'pride, domination',
  },
  {
    id: 'MAJ_09',
    name: 'The Hermit',
    arcana: 'Major',
    suit: null,
    rank: '9',
    element: 'Earth',
    astro: { type: 'sign', key: 'Virgo' },
    house_hook: 6,
    hebrew: 'Yod',
    decan_index: 0,
    poem_slot: 'P10',
    upright: 'search, guide',
    shadow: 'isolation, withdrawal',
  },
  {
    id: 'MAJ_10',
    name: 'Wheel of Fortune',
    arcana: 'Major',
    suit: null,
    rank: '10',
    element: 'Fire',
    astro: { type: 'planet', key: 'Jupiter' },
    house_hook: 9,
    hebrew: 'Kaph',
    decan_index: 0,
    poem_slot: 'P11',
    upright: 'turn, chance',
    shadow: 'resistance, gamble',
  },
  {
    id: 'MAJ_11',
    name: 'Justice',
    arcana: 'Major',
    suit: null,
    rank: '11',
    element: 'Air',
    astro: { type: 'sign', key: 'Libra' },
    house_hook: 7,
    hebrew: 'Lamed',
    decan_index: 0,
    poem_slot: 'P12',
    upright: 'balance, truth',
    shadow: 'judgment, bias',
  },
  {
    id: 'MAJ_12',
    name: 'The Hanged Man',
    arcana: 'Major',
    suit: null,
    rank: '12',
    element: 'Water',
    astro: { type: 'element', key: 'Water' },
    house_hook: 0,
    hebrew: 'Mem',
    decan_index: 0,
    poem_slot: 'P13',
    upright: 'surrender, pause',
    shadow: 'stall, martyr',
  },
  {
    id: 'MAJ_13',
    name: 'Death',
    arcana: 'Major',
    suit: null,
    rank: '13',
    element: 'Water',
    astro: { type: 'sign', key: 'Scorpio' },
    house_hook: 8,
    hebrew: 'Nun',
    decan_index: 0,
    poem_slot: 'P14',
    upright: 'release, transform',
    shadow: 'clinging, dread',
  },
  {
    id: 'MAJ_14',
    name: 'Temperance',
    arcana: 'Major',
    suit: null,
    rank: '14',
    element: 'Fire',
    astro: { type: 'sign', key: 'Sagittarius' },
    house_hook: 9,
    hebrew: 'Samekh',
    decan_index: 0,
    poem_slot: 'P15',
    upright: 'blend, flow',
    shadow: 'spillage, excess',
  },
  {
    id: 'MAJ_15',
    name: 'The Devil',
    arcana: 'Major',
    suit: null,
    rank: '15',
    element: 'Earth',
    astro: { type: 'sign', key: 'Capricorn' },
    house_hook: 10,
    hebrew: 'Ayin',
    decan_index: 0,
    poem_slot: 'P16',
    upright: 'bond, material',
    shadow: 'addiction, fear',
  },
  {
    id: 'MAJ_16',
    name: 'The Tower',
    arcana: 'Major',
    suit: null,
    rank: '16',
    element: 'Fire',
    astro: { type: 'planet', key: 'Mars' },
    house_hook: 1,
    hebrew: 'Peh',
    decan_index: 0,
    poem_slot: 'P17',
    upright: 'shock, upheaval',
    shadow: 'denial, collapse',
  },
  {
    id: 'MAJ_17',
    name: 'The Star',
    arcana: 'Major',
    suit: null,
    rank: '17',
    element: 'Air',
    astro: { type: 'sign', key: 'Aquarius' },
    house_hook: 11,
    hebrew: 'Tzaddi',
    decan_index: 0,
    poem_slot: 'P18',
    upright: 'hope, clarity',
    shadow: 'distance, delusion',
  },
  {
    id: 'MAJ_18',
    name: 'The Moon',
    arcana: 'Major',
    suit: null,
    rank: '18',
    element: 'Water',
    astro: { type: 'sign', key: 'Pisces' },
    house_hook: 12,
    hebrew: 'Qoph',
    decan_index: 0,
    poem_slot: 'P19',
    upright: 'dream, tides',
    shadow: 'anxiety, mirage',
  },
  {
    id: 'MAJ_19',
    name: 'The Sun',
    arcana: 'Major',
    suit: null,
    rank: '19',
    element: 'Fire',
    astro: { type: 'planet', key: 'Sun' },
    house_hook: 5,
    hebrew: 'Resh',
    decan_index: 0,
    poem_slot: 'P20',
    upright: 'vitality, joy',
    shadow: 'burn, exposed',
  },
  {
    id: 'MAJ_20',
    name: 'Judgement',
    arcana: 'Major',
    suit: null,
    rank: '20',
    element: 'Fire',
    astro: { type: 'planet', key: 'Pluto' },
    house_hook: 8,
    hebrew: 'Shin',
    decan_index: 0,
    poem_slot: 'P21',
    upright: 'wake, reckon',
    shadow: 'avoidance, stagnate',
  },
  {
    id: 'MAJ_21',
    name: 'The World',
    arcana: 'Major',
    suit: null,
    rank: '21',
    element: 'Earth',
    astro: { type: 'planet', key: 'Saturn' },
    house_hook: 10,
    hebrew: 'Tav',
    decan_index: 0,
    poem_slot: 'P22',
    upright: 'wholeness, completion',
    shadow: 'closure, stuck',
  },
];
